### ISSUE TITLE
lacking of dependency

### ISSUE THREAD

**Issue by jiderlesi** [orangepi-xunlong/openwrt#12]
WARNING: Makefile 'package/feeds/luci/luci-app-firewall/Makefile' has a dependency on 'uci-firewall', which does not exist
WARNING: Makefile 'package/feeds/packages/qemu/Makefile' has a dependency on 'libfdt', which does not exist
WARNING: Makefile 'package/feeds/packages/qemu/Makefile' has a dependency on 'libfdt', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-firewall/Makefile' has a dependency on 'uci-firewall', which does not exist
WARNING: Makefile 'package/feeds/packages/qemu/Makefile' has a dependency on 'libfdt', which does not exist
WARNING: Makefile 'package/feeds/packages/qemu/Makefile' has a dependency on 'libfdt', which does not exist

**Comment by baiywt** [comment]
Master branch has been updated, you can test it.
https://github.com/orangepi-xunlong/openwrt/tree/master
