### ISSUE TITLE
YT8531C

### ISSUE THREAD

**Issue by DRTEK** [orangepi-xunlong/openwrt#13]
Hello 
when i add eth0 to eth1 in bridge mode 
the interface doesn't work properly have you had experience this ?
thanks

**Comment by baiywt** [comment]
Hi, could you please provide a test method in detail ?

**Comment by DRTEK** [comment]
Hello 
with stock firmware ,here is the network config  file contents and dmesg output 
link gets up but no traffic goes through from eth0

hope this helps


config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd62:8113:275a::/48'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'eth0'
        list ports 'eth1'

config device
        option name 'eth1'
        option macaddr '<redacted>'

config interface 'lan'
        option device 'br-lan'
        option proto 'dhcp'

config device
        option name 'eth0'
        option macaddr  '<redacted>-1'




[  202.978363] phy_yt8531_led_fixup in
[  202.980857] rk_gmac-dwmac ff540000.ethernet eth0: PHY [stmmac-0:00] driver [YT8531 Gigabit Ethernet] (irq=POLL)
[  203.032437] rk_gmac-dwmac ff540000.ethernet eth0: No Safety Features support found
[  203.033149] rk_gmac-dwmac ff540000.ethernet eth0: PTP not supported by HW
[  203.033773] rk_gmac-dwmac ff540000.ethernet eth0: configuring for phy/rgmii link mode
[  203.037308] br-lan: port 1(eth0) entered blocking state
[  203.037794] br-lan: port 1(eth0) entered disabled state
[  203.038897] device eth0 entered promiscuous mode
[  203.052731] br-lan: port 2(eth1) entered blocking state
[  203.053219] br-lan: port 2(eth1) entered disabled state
[  203.054209] device eth1 entered promiscuous mode
[  203.057595] br-lan: port 2(eth1) entered blocking state
[  203.058079] br-lan: port 2(eth1) entered forwarding state
[  203.060097] r8152 4-1:1.0 eth1: Promiscuous mode enabled
[  203.763417] br-lan: port 2(eth1) entered disabled state
[  204.915737] device eth0 left promiscuous mode
[  204.916278] br-lan: port 1(eth0) entered disabled state
[  204.968772] device eth1 left promiscuous mode
[  204.969708] br-lan: port 2(eth1) entered disabled state
[  205.257773] phy_yt8531_led_fixup in
[  205.260261] rk_gmac-dwmac ff540000.ethernet eth0: PHY [stmmac-0:00] driver [YT8531 Gigabit Ethernet] (irq=POLL)
[  205.312455] rk_gmac-dwmac ff540000.ethernet eth0: No Safety Features support found
[  205.313168] rk_gmac-dwmac ff540000.ethernet eth0: PTP not supported by HW
[  205.313792] rk_gmac-dwmac ff540000.ethernet eth0: configuring for phy/rgmii link mode
[  205.317509] br-lan: port 1(eth0) entered blocking state
[  205.318003] br-lan: port 1(eth0) entered disabled state
[  205.319072] device eth0 entered promiscuous mode
[  205.330907] br-lan: port 2(eth1) entered blocking state
[  205.331391] br-lan: port 2(eth1) entered disabled state
[  205.332248] device eth1 entered promiscuous mode
[  207.363856] rk_gmac-dwmac ff540000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  207.364726] br-lan: port 1(eth0) entered blocking state
[  207.365202] br-lan: port 1(eth0) entered forwarding state
[  207.366341] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[  208.136027] r8152 4-1:1.0 eth1: Promiscuous mode enabled
[  208.136833] r8152 4-1:1.0 eth1: carrier on
[  208.137845] br-lan: port 2(eth1) entered blocking state
[  208.138322] br-lan: port 2(eth1) entered forwarding state

**Comment by DRTEK** [comment]
fyi : mac addresses were redacted

**Comment by baiywt** [comment]
Hi, the YT8531C driver has been updated, you can compile and test it again.
https://github.com/orangepi-xunlong/openwrt/commit/2b78fb57d55274508bed4af116ab7afd6ba51146

**Comment by DRTEK** [comment]
it is working as expected , thank you for your help
