### ISSUE TITLE
SPI boot 

### ISSUE THREAD

**Issue by DRTEK** [orangepi-xunlong/openwrt#14]
Hello , 
I am trying to boot firmware from spi flash
before starting flash the chip, i get this warning in dmesg

[    0.152963] spi-nor spi0.0: unrecognized JEDEC id bytes: 5e 40 18 5e 40 18
[    0.153642] spi-nor: probe of spi0.0 failed with error -2

can you give me pointers ?
thanks

**Comment by baiywt** [comment]
[ 0.152963] spi-nor spi0.0: unrecognized JEDEC id bytes: 5e 40 18 5e 40 18
[ 0.153642] spi-nor: probe of spi0.0 failed with error -2

This issue has been resolved, you can download the latest source code for testing.
https://github.com/orangepi-xunlong/openwrt/commit/a56ce0f7e8cf7186b76e33c54dd7b2e090714c15

**Comment by DRTEK** [comment]
Hello,
it identifies the spi chip 
would it be possible to make a factory image to write to spi with uboot  kernel and rootfs altogether.
can you help on this feature as well 
thank you so much for your help

**Comment by baiywt** [comment]
Sorry, this feature is not currently supported

**Comment by baiywt** [comment]
@DRTEK Hello, Spi Flash startup is now supported.
https://github.com/orangepi-xunlong/openwrt/commit/a1274d84e5b6bf1f7c5e3ea4f138b44256650292
https://github.com/baiywt/openwrt-spi-boot-for-r1p-r1pl

**Comment by DRTEK** [comment]
thank you so much for doing this 
cheers
