### ISSUE TITLE
missing  arm-trusted-firmware-rk3328

### ISSUE THREAD

**Issue by mingxiaoyu** [orangepi-xunlong/openwrt#15]
+ curl -f --connect-timeout 20 --retry 5 --location --insecure https://sources.cdn.openwrt.org/arm-trusted-firmware-rk3328-2021-06-01-7d631e0d.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

**Comment by baiywt** [comment]
您好，这个问题可以复现吗？我测试没有遇到这个错误。

**Comment by mingxiaoyu** [comment]
https://github.com/baiywt/R1PlusLTS-OpenWrt/actions/runs/1896147779
你自己的也复现了

**Comment by orangepi-xunlong** [comment]
你好，你测试的是哪个分支的代码？

**Comment by mingxiaoyu** [comment]
> 你好，你测试的是哪个分支的代码？

21.02

**Comment by mingxiaoyu** [comment]
@baiywt @orangepi-xunlong  it is working now. may be it is network issue. :)
