### ISSUE TITLE
编译找不到webadmin包

### ISSUE THREAD

**Issue by luoei** [orangepi-xunlong/openwrt#17]
make menuconfig 里找不到这个包，编译完后，ssh可以访问，http打不开，要咋个解决呢？

**Comment by baiywt** [comment]
请问是打不开luci管理界面吗？确认一下luci相关的包有没有编译进去，使用configs/OrangePi_R1_Plus_LTS_defconfig这个配置文件编译试试

**Comment by luoei** [comment]
后来发现 把admin相关的勾选还有主题编译进去，就可以显示了。

**Comment by baiywt** [comment]
这个仓库是基于openwrt官方的，没有webadmin包
