### ISSUE TITLE
Soft Reboot Hangs

### ISSUE THREAD

**Issue by DRTEK** [orangepi-xunlong/openwrt#18]
[   34.721578] reboot: Restarting system
INFO:    PSCI Power Domain Map:
INFO:      Domain Node : Level 2, parent_node -1, State ON (0x0)
INFO:      Domain Node : Level 1, parent_node 0, State ON (0x0)
INFO:      Domain Node : Level 0, parent_node 0, State ON (0x0)
INFO:      Domain Node : Level 0, parent_node 0, State ON (0x0)
INFO:      CPU Node : MPID 0x0, parent_node 1, State ON (0x0)
INFO:      CPU Node : MPID 0x1, parent_node 1, State ON (0x0)
INFO:      CPU Node : MPID 0x2, parent_node 1, State ON (0x0)
INFO:      CPU Node : MPID 0x3, parent_node 1, State ON (0x0)

**Comment by DRTEK** [comment]
any feedbacks ?
thank you

**Comment by baiywt** [comment]
After testing, it is found that this issue may appear on some SDcard, so I made the following changes https://github.com/orangepi-xunlong/openwrt/commit/14d3a99e17f2ec6097eeef97530cba2d62c58d3c, but still need a lot of test.

**Comment by DRTEK** [comment]
Hello ,
i have tested on the same sd card and it seems to be stable now
Thank you
