### ISSUE TITLE
因为openwrt的一些库迁移导致无法编译成功

### ISSUE THREAD

**Issue by garlicsoft** [orangepi-xunlong/openwrt#3]
git.openwrt.org/feed/packages.git
的一些包已迁移到openwrt内部，导致依赖缺失，目前使用该库已无法顺利完成编译

**Comment by orangepi-xunlong** [comment]
已修复 [5e94f6e](https://github.com/orangepi-xunlong/openwrt/commit/37368e77a529c7e194f0bb91f01675e75f94ff78)，thanks!
