### ISSUE TITLE
Please include the following packages in the next release build.

### ISSUE THREAD

**Issue by kgoerbig** [orangepi-xunlong/openwrt#4]
adblock
banip
blkid
bmon
dmesg
e2fsprogs
fdisk
htop
ifstat
iftop
iperf
iperf3
nano
rsync
speedtest-netperf
tcpdump
luci-app-adblock
luci-app-advanced-reboot
luci-app-aria2
luci-app-banip
luci-app-commands
luci-app-ddns
luci-app-mjpg-streamer
luci-app-nextdns
luci-app-nlbwmon
luci-app-ntpc
luci-app-openvpn
luci-app-qos
luci-app-samba4
luci-app-simple-adblock
luci-app-squid
luci-app-sqm
luci-app-transmission
luci-app-unbound
luci-app-vnstat
luci-app-vnstat2
luci-app-watchcat
luci-app-minidlna
luci-app-nlbwmon
luci-app-ntpc
luci-app-squid
luci-app-sqm
luci-app-statistics
luci-proto-wireguard
wireguard-tools
luci-app-wireguard

**Comment by orangepi-xunlong** [comment]
Most packages have been added. If not, please try to install them manually.

**Comment by kgoerbig** [comment]
Thank you very much!

**Comment by orangepi-xunlong** [comment]
You're welcome!

**Comment by mademlacloi** [comment]
Please add package
mwan3
Vlan

I dont install vlan.
