### ISSUE TITLE
Kernel is incompatible with wireguard

### ISSUE THREAD

**Issue by Sunvas** [orangepi-xunlong/openwrt#5]
While trying installing wireguard, I get the error of incompatibility of the kernel's version. See screenshot below:
https://postimg.cc/zLCLXLD4

**Comment by orangepi-xunlong** [comment]
Resolved, please use the latest openwrt image. 

http://www.orangepi.org/downloadresources/orangepiR1Plus/2020-12-22/orangepiR1357b4fd6e8b12f7bc81d7e40e7.html
