### ISSUE TITLE
关于 Orange Pi R1 Plus  CPU风扇控制

### ISSUE THREAD

**Issue by honkerjin** [orangepi-xunlong/openwrt#8]
主机型号 | Xunlong Orange Pi R1 Plus (CpuMark : 9643.465730 Scores)
架构 | ARMv8 Processor x 4 (1200MHz, 73.8°C )
固件版本 | OpenWrt R21.8.6 / LuCI Master (git-21.211.30217-03784c3)
内核版本 | 5.4.138

官方及lean大固件都没有相关风扇控制的固件或者脚本，请教一下，如何可以做到温控风扇。如温度超过60风扇开始，小于60停止。

**Comment by honkerjin** [comment]
顺便说一句，开发板的温度是真的高，3%的负载已经73度了，我还加了大的散热块

**Comment by orangepi-xunlong** [comment]
你好，如果风扇是接到Orange Pi R1 Plus的两pin的风扇专用接口，是没法通过程序控制风扇开关的。
如果想控制风扇，只能把风扇的一个引脚通过杜邦线接到13pin的GPIO口上，另一端接GND，这样就能通过GPIO口来控制风扇。
目前没有相关实现的脚本或者固件，如果有需求需要自己实现下。
